# -*- mode: python ; coding: utf-8 -*-

added_files = [
    ('resources/phase diagram bg.svg', 'resources/'),
    ('resources/phase diagram bg light.svg', 'resources/'),
    ('resources/phase diagram foc dark.svg', 'resources/'),
    ('resources/phase diagram stereostim dark.svg', 'resources/'),
    ('resources/favicon.png', 'resources/'),
    ('resources/icons', 'resources/icons'),
    ('resources/media_players', 'resources/media_players'),
    ('resources/wizard', 'resources/wizard'),
    ('coyote_plugin', 'coyote_plugin'),
    ('ui_mods', 'ui_mods'),
    ('device/coyote', 'device/coyote'),
]

a = Analysis(
    ['restim.py'],
    pathex=[],
    binaries=[],
    datas=added_files,
    hiddenimports=[
        'coyote_plugin',
        'coyote_plugin.runtime_plugin',
        'coyote_plugin.wizard_integration',
        'coyote_plugin.algorithm_factory',
        'coyote_plugin.settings',
        'coyote_plugin.params',
        'coyote_plugin.device',
        'coyote_plugin.device.constants',
        'coyote_plugin.device.device',
        'device.coyote',
        'device.coyote.coyote_device',
        'ui_mods',
        'ui_mods.theme',
        'ui_mods.icon_loader',
        'ui_mods.settings',
    ],
    hookspath=['pyinstaller-hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='restim',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['resources\\favicon.ico'],
)
